// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenFinancialExchange.Infrastructure.Persistence;

#nullable disable

namespace OpenFinancialExchange.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625193546_AddCategoryKeywords")]
    partial class AddCategoryKeywords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.BankAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AcctId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AcctId");

                    b.Property<string>("AcctType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("AcctType");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("BankId");

                    b.Property<string>("BranchId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("BranchId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<long>("FinancialInstitutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("FinancialInstitutionId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("FinancialInstitutionId");

                    b.HasIndex("UserId", "BankId", "BranchId", "AcctId")
                        .IsUnique()
                        .HasDatabaseName("UQ_BankAccounts_User_BankId_BranchId_AcctId")
                        .HasFilter("[BranchId] IS NOT NULL");

                    b.ToTable("BankAccounts", (string)null);
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.BankCode", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<int>("CodigoCompensacao")
                        .HasColumnType("int");

                    b.Property<string>("NomeInstituicao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Segmento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCompensacao")
                        .IsUnique()
                        .HasDatabaseName("UX_BankCodes_CodigoCompensacao");

                    b.ToTable("BankCodes", (string)null);
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Categories_User_Name")
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Color = "#ef4444",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInternal = false,
                            IsSystem = true,
                            Keywords = "PANIFICADORA\nPADARIA\nRESTAURANTE\nSUPERMERCADO\nMERCADO\nHORTIFRUTI\nACOUGUE\nLANCHONETE\nIFOOD\nRAPPI",
                            Kind = "DEBIT",
                            Name = "Alimentação",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2L,
                            Color = "#f97316",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInternal = false,
                            IsSystem = true,
                            Keywords = "POSTO\nCOMBUSTIVEL\nGASOLINA\nESTACIONAMENTO\nUBER\n99 TECNOLOGIA\n99POP\nPEDAGIO\nONIBUS\nMETRO",
                            Kind = "DEBIT",
                            Name = "Transporte",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3L,
                            Color = "#eab308",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInternal = false,
                            IsSystem = true,
                            Keywords = "ALUGUEL\nCONDOMINIO\nENERGIA\nENEL\nCEMIG\nSABESP\nAGUA\nINTERNET\nVIVO FIBRA\nCLARO NET",
                            Kind = "DEBIT",
                            Name = "Moradia",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4L,
                            Color = "#14b8a6",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInternal = false,
                            IsSystem = true,
                            Keywords = "FARMACIA\nDROGARIA\nDROGASIL\nRAIA\nPACHECO\nHOSPITAL\nCLINICA\nLABORATORIO\nUNIMED\nDENTISTA",
                            Kind = "DEBIT",
                            Name = "Saúde",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5L,
                            Color = "#3b82f6",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInternal = false,
                            IsSystem = true,
                            Keywords = "ESCOLA\nCOLEGIO\nFACULDADE\nUNIVERSIDADE\nCURSO\nUDEMY\nALURA\nLIVRARIA",
                            Kind = "DEBIT",
                            Name = "Educação",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6L,
                            Color = "#a855f7",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInternal = false,
                            IsSystem = true,
                            Keywords = "CINEMA\nNETFLIX\nSPOTIFY\nDISNEY\nHBO\nAMAZON PRIME\nINGRESSO\nTEATRO\nSTEAM",
                            Kind = "DEBIT",
                            Name = "Lazer",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7L,
                            Color = "#ec4899",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInternal = false,
                            IsSystem = true,
                            Keywords = "MAGAZINE\nMAGALU\nAMERICANAS\nMERCADO LIVRE\nMERCADOLIVRE\nAMAZON\nSHOPEE\nALIEXPRESS\nSHOPPING\nRENNER\nRIACHUELO",
                            Kind = "DEBIT",
                            Name = "Compras",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8L,
                            Color = "#64748b",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInternal = false,
                            IsSystem = true,
                            Keywords = "BARBEARIA\nSALAO\nLAVANDERIA\nASSINATURA",
                            Kind = "DEBIT",
                            Name = "Serviços",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9L,
                            Color = "#22c55e",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInternal = false,
                            IsSystem = true,
                            Keywords = "SALARIO\nFOLHA PGTO\nFOLHA DE PAGAMENTO\nPROVENTOS\nREMUNERACAO\nORDENADO",
                            Kind = "CREDIT",
                            Name = "Salário",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10L,
                            Color = "#10b981",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInternal = true,
                            IsSystem = true,
                            Keywords = "RESGATE\nAPLICACAO\nAPLICACAO INV\nINV FAC\nINVEST FACIL\nINVESTIMENTO FACIL\nCDB\nTESOURO DIRETO\nFUNDO",
                            Kind = "BOTH",
                            Name = "Investimentos",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11L,
                            Color = "#06b6d4",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInternal = true,
                            IsSystem = true,
                            Keywords = "",
                            Kind = "BOTH",
                            Name = "Transferências",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12L,
                            Color = "#f43f5e",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInternal = false,
                            IsSystem = true,
                            Keywords = "TARIFA\nCESTA\nANUIDADE\nIOF\nPACOTE SERVICOS\nMANUTENCAO CONTA",
                            Kind = "DEBIT",
                            Name = "Tarifas Bancárias",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13L,
                            Color = "#94a3b8",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsInternal = false,
                            IsSystem = true,
                            Keywords = "",
                            Kind = "BOTH",
                            Name = "Outros",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.FinancialInstitution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("BankId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Fid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Fid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("OrgName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("OrgName");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "BankId", "Fid")
                        .IsUnique()
                        .HasDatabaseName("UQ_FinancialInstitutions_User_BankId_Fid")
                        .HasFilter("[Fid] IS NOT NULL");

                    b.ToTable("FinancialInstitutions", (string)null);
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.OfxBalance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BalAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BalanceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtAsOf")
                        .HasColumnType("datetime2");

                    b.Property<long>("StatementId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("StatementId");

                    b.HasIndex("UserId");

                    b.ToTable("OfxBalances", (string)null);
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.OfxImport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Charset")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Compression")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Encoding")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewFileUid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OfxData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OfxData");

                    b.Property<short?>("OfxHeaderVersion")
                        .HasColumnType("smallint")
                        .HasColumnName("OfxHeaderVersion");

                    b.Property<short?>("OfxVersion")
                        .HasColumnType("smallint")
                        .HasColumnName("OfxVersion");

                    b.Property<string>("OldFileUid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Security")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "FileHash")
                        .IsUnique()
                        .HasDatabaseName("UQ_OfxImports_User_FileHash");

                    b.ToTable("OfxImports", (string)null);
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.OfxStatement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BankAccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurDef")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime?>("DtEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtServer")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtStart")
                        .HasColumnType("datetime2");

                    b.Property<long>("ImportId")
                        .HasColumnType("bigint");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<short?>("StatusCode")
                        .HasColumnType("smallint");

                    b.Property<string>("StatusSeverity")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TrnUid")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId");

                    b.HasIndex("ImportId");

                    b.HasIndex("UserId");

                    b.ToTable("OfxStatements", (string)null);
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.OfxTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("CheckNum")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtPosted")
                        .HasColumnType("datetime2");

                    b.Property<string>("FitId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Memo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("StatementId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TrnAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrnType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_OfxTransactions_CategoryId");

                    b.HasIndex("StatementId", "FitId")
                        .IsUnique()
                        .HasDatabaseName("UIX_OfxTransactions_StatementId_FitId")
                        .HasFilter("[FitId] IS NOT NULL");

                    b.HasIndex("UserId", "DtPosted", "TrnType")
                        .HasDatabaseName("IX_OfxTransactions_User_DtPosted_TrnType");

                    b.ToTable("OfxTransactions", (string)null);
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.BankAccount", b =>
                {
                    b.HasOne("OpenFinancialExchange.Domain.Entities.FinancialInstitution", null)
                        .WithMany()
                        .HasForeignKey("FinancialInstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_BankAccounts_FinancialInstitutions");

                    b.HasOne("OpenFinancialExchange.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_BankAccounts_Users");
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.Category", b =>
                {
                    b.HasOne("OpenFinancialExchange.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Categories_Users");
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.FinancialInstitution", b =>
                {
                    b.HasOne("OpenFinancialExchange.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FinancialInstitutions_Users");
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.OfxBalance", b =>
                {
                    b.HasOne("OpenFinancialExchange.Domain.Entities.OfxStatement", null)
                        .WithMany("Balances")
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OfxBalances_OfxStatements");

                    b.HasOne("OpenFinancialExchange.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_OfxBalances_Users");
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.OfxImport", b =>
                {
                    b.HasOne("OpenFinancialExchange.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_OfxImports_Users");
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.OfxStatement", b =>
                {
                    b.HasOne("OpenFinancialExchange.Domain.Entities.BankAccount", null)
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_OfxStatements_BankAccounts");

                    b.HasOne("OpenFinancialExchange.Domain.Entities.OfxImport", null)
                        .WithMany()
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OfxStatements_OfxImports");

                    b.HasOne("OpenFinancialExchange.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_OfxStatements_Users");
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.OfxTransaction", b =>
                {
                    b.HasOne("OpenFinancialExchange.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_OfxTransactions_Categories");

                    b.HasOne("OpenFinancialExchange.Domain.Entities.OfxStatement", null)
                        .WithMany("Transactions")
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OfxTransactions_OfxStatements");

                    b.HasOne("OpenFinancialExchange.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_OfxTransactions_Users");
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.OfxStatement", b =>
                {
                    b.Navigation("Balances");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
