// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenFinancialExchange.Infrastructure.Persistence;

#nullable disable

namespace OpenFinancialExchange.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.BankAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AcctId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AcctId");

                    b.Property<string>("AcctType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("AcctType");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("BankId");

                    b.Property<string>("BranchId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("BranchId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<long>("FinancialInstitutionId")
                        .HasColumnType("bigint")
                        .HasColumnName("FinancialInstitutionId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("FinancialInstitutionId");

                    b.HasIndex("BankId", "BranchId", "AcctId")
                        .IsUnique()
                        .HasDatabaseName("UQ_BankAccounts_BankId_BranchId_AcctId")
                        .HasFilter("[BranchId] IS NOT NULL");

                    b.ToTable("BankAccounts", (string)null);
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.BankCode", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<int>("CodigoCompensacao")
                        .HasColumnType("int");

                    b.Property<string>("NomeInstituicao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Segmento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCompensacao")
                        .IsUnique()
                        .HasDatabaseName("UX_BankCodes_CodigoCompensacao");

                    b.ToTable("BankCodes", (string)null);
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.FinancialInstitution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("BankId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Fid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Fid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("OrgName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("OrgName");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("BankId", "Fid")
                        .IsUnique()
                        .HasDatabaseName("UQ_FinancialInstitutions_BankId_Fid")
                        .HasFilter("[Fid] IS NOT NULL");

                    b.ToTable("FinancialInstitutions", (string)null);
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.OfxBalance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BalAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BalanceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtAsOf")
                        .HasColumnType("datetime2");

                    b.Property<long>("StatementId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StatementId");

                    b.ToTable("OfxBalances", (string)null);
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.OfxImport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Charset")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Compression")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Encoding")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewFileUid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OfxData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OfxData");

                    b.Property<short?>("OfxHeaderVersion")
                        .HasColumnType("smallint")
                        .HasColumnName("OfxHeaderVersion");

                    b.Property<short?>("OfxVersion")
                        .HasColumnType("smallint")
                        .HasColumnName("OfxVersion");

                    b.Property<string>("OldFileUid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Security")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("FileHash")
                        .IsUnique()
                        .HasDatabaseName("UQ_OfxImports_FileHash");

                    b.ToTable("OfxImports", (string)null);
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.OfxStatement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BankAccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurDef")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime?>("DtEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtServer")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtStart")
                        .HasColumnType("datetime2");

                    b.Property<long>("ImportId")
                        .HasColumnType("bigint");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<short?>("StatusCode")
                        .HasColumnType("smallint");

                    b.Property<string>("StatusSeverity")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TrnUid")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId");

                    b.HasIndex("ImportId");

                    b.ToTable("OfxStatements", (string)null);
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.OfxTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CheckNum")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtPosted")
                        .HasColumnType("datetime2");

                    b.Property<string>("FitId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Memo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("StatementId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TrnAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrnType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DtPosted", "TrnType")
                        .HasDatabaseName("IX_OfxTransactions_DtPosted_TrnType");

                    b.HasIndex("StatementId", "FitId")
                        .IsUnique()
                        .HasDatabaseName("UIX_OfxTransactions_StatementId_FitId")
                        .HasFilter("[FitId] IS NOT NULL");

                    b.ToTable("OfxTransactions", (string)null);
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.BankAccount", b =>
                {
                    b.HasOne("OpenFinancialExchange.Domain.Entities.FinancialInstitution", null)
                        .WithMany()
                        .HasForeignKey("FinancialInstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_BankAccounts_FinancialInstitutions");
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.OfxBalance", b =>
                {
                    b.HasOne("OpenFinancialExchange.Domain.Entities.OfxStatement", null)
                        .WithMany("Balances")
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OfxBalances_OfxStatements");
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.OfxStatement", b =>
                {
                    b.HasOne("OpenFinancialExchange.Domain.Entities.BankAccount", null)
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_OfxStatements_BankAccounts");

                    b.HasOne("OpenFinancialExchange.Domain.Entities.OfxImport", null)
                        .WithMany()
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OfxStatements_OfxImports");
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.OfxTransaction", b =>
                {
                    b.HasOne("OpenFinancialExchange.Domain.Entities.OfxStatement", null)
                        .WithMany("Transactions")
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OfxTransactions_OfxStatements");
                });

            modelBuilder.Entity("OpenFinancialExchange.Domain.Entities.OfxStatement", b =>
                {
                    b.Navigation("Balances");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
